
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Sep 23 14:41:06 CEST 2016
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PP = 31;
  public static final int MM = 32;
  public static final int RIGHT_BRACKET = 7;
  public static final int CHAR = 37;
  public static final int CONST = 12;
  public static final int ASSIGNMENT = 10;
  public static final int SEMIC = 5;
  public static final int RIGHT_SBRACKET = 9;
  public static final int LEFT_CBRACKET = 3;
  public static final int AND = 34;
  public static final int OR = 33;
  public static final int BOOL = 38;
  public static final int COMMA = 11;
  public static final int CLASS = 13;
  public static final int DIV = 43;
  public static final int NUM = 36;
  public static final int IF = 20;
  public static final int DOT = 17;
  public static final int LE = 29;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 42;
  public static final int LEFT_SBRACKET = 8;
  public static final int ADD = 40;
  public static final int MOD = 44;
  public static final int NEQ = 26;
  public static final int IDENT = 35;
  public static final int BREAK = 23;
  public static final int VOID = 24;
  public static final int GTE = 28;
  public static final int EQU = 25;
  public static final int ELSE = 21;
  public static final int READ = 16;
  public static final int WHILE = 22;
  public static final int EXTENDS = 19;
  public static final int LEQ = 30;
  public static final int STRING = 39;
  public static final int RIGHT_CBRACKET = 4;
  public static final int GT = 27;
  public static final int SUB = 41;
  public static final int LEFT_BRACKET = 6;
  public static final int PRINT = 15;
}

